services:
  telegram-entities-html:
    image: asokol1981/telegram-entities-html
    container_name: telegram-entities-html
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - "./:/app"
      - ./docker/entrypoint.sh:/entrypoint.sh
      - "home_user:/home/appuser/"
    working_dir: /app
    user: appuser
    extra_hosts:
      - host.docker.internal:host-gateway
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    entrypoint: ["/entrypoint.sh"]
    networks:
      - net

networks:
  net:

volumes:
  home_user:
    driver: local
